RED again.
Sage-Bionetworks/Synapse-Stack-Builder pull request #175
Opened 2018-03-30 01:03 UTC by xschildw

Passed validate-template.

2018-03-30 10:54 UTC, xschildw commented on infra/cf_templates/synapse_vpc.yml
>        CIDR: "0.0/20"
Should we reduce the size of each subnet in case we need more of them?

2018-03-30 19:38 UTC, xschildw commented on infra/cf_templates/synapse_vpc.yml
> +    Value: !Ref REDPRIVATE2Subnet
Fix description

2018-03-30 20:36 UTC, zaro0508 requested changes
looks good except for the small mistake.

2018-03-30 20:36 UTC, zaro0508 commented on infra/cf_templates/synapse_vpc.yml
> +    Default: "10.20.0.0/16"
this is the CIDR of the sophos vpn, so should stay '10.1.0.0/16'

2018-03-31 07:21 UTC, xschildw commented on infra/cf_templates/synapse_vpc.yml
> +    Default: "10.20.0.0/16"
Good catch! Will fix.

2018-04-02 18:30 UTC, xschildw commented
Reviewed with Khai. Pulling in.

2018-04-02 18:30 UTC, merged