[PLFM-6623] Add bucket + one stream
Sage-Bionetworks/Synapse-Stack-Builder pull request #370
Opened 2021-03-24 17:56 UTC by xschildw

[PLFM-6623] Just add the bucket and setup a stream

2021-04-08 19:49 UTC, marcomarasca requested changes

2021-04-08 19:49 UTC, marcomarasca commented on src/main/resources/templates/repo/kinesis-log-streams.json
> +		"bucket": "${stack}.analytics.sagebase.org",
Maybe a dedicated bucket for snapshots instead might be better, e.g. ${stack}.snapshots.sagebase.org. We need to be careful not to use the same "snapshot" bucket used previously.

2021-04-08 19:53 UTC, marcomarasca commented on src/main/resources/templates/repo/kinesis-log-streams.json
> +		"partitionScheme": "!{timestamp:yyyy-MM-dd}",
For the partition scheme, you might want to use a hive format (basically the name of the folder encode the partition column) because it's much easier to query from a glue table (e.g. you can create projections): 

"dt=!{timestamp:yyyy-MM-dd}" or even better (depending on how we filter this data):

"year=!{timestamp:yyyy}/month=!{timestamp:MM}/day=!{timestamp:dd}"

2021-04-13 04:28 UTC, closed without merging

2021-04-13 04:28 UTC, xschildw commented
Redo.