PLFM-6824
Sage-Bionetworks/Synapse-Stack-Builder pull request #451
Opened 2022-03-04 17:54 UTC by xschildw

2022-03-08 00:13 UTC, xschildw commented on scripts/create_cw_dashboard/create_dashboard_app.py
> +    stack_versions = included_versions(stack_version, 3)
Change this to get the  most recent versions

2022-03-08 00:14 UTC, xschildw commented on scripts/create_cw_dashboard/cloudwatchmetrics_instances_history.py
> +import os
Save all the files to S3 bucket so it can work from Jenkins.

2022-03-08 00:14 UTC, xschildw commented on scripts/create_cw_dashboard/create_dashboard_app.py
> +# TODO: Simplify, namespaces can be generated
Not needed, treat all ids the same way.

2022-03-17 21:00 UTC, marcomarasca requested changes

2022-03-17 21:00 UTC, marcomarasca commented on scripts/create_cw_dashboard/cloudwatchmetrics_instances_history.py
> +      bucket.download_file(o.key, target_path)
Instead of using the file system as a cache we can just store it in memory

2022-03-17 21:00 UTC, marcomarasca commented on scripts/create_cw_dashboard/cloudwatchmetrics_instances_history.py
> +      bucket = s3.Bucket(self.history_bucket_name)
Maybe use a static prefix where this files are stored

2022-09-22 00:21 UTC, xschildw commented
This needs to be redone completely in Java.

2022-09-22 00:21 UTC, closed without merging