PLFM-7490: Enable RDS monitoring
Sage-Bionetworks/Synapse-Stack-Builder pull request #485
Opened 2022-10-05 15:38 UTC by xschildw

This PR enables RDS enhanced monitoring and insights on prod RDS instances.

2022-10-05 17:09 UTC, marcomarasca requested changes

2022-10-05 17:09 UTC, marcomarasca commented on src/main/resources/templates/repo/main-repo-shared-resources-template.json.vpt
> +                #if((${stack} == 'prod') && (${EnableRdsEnhancedMonitoring} == "true"))
Maybe we can ignore the "prod" switch here and put this property in the "repo-defaults.properties" that is used to build each DB descriptor. In this way we can set it to false by default and enabled it only in the prod deployment.

2022-10-05 17:12 UTC, marcomarasca commented on src/main/resources/templates/repo/main-repo-shared-resources-template.json.vpt
> +                "MonitoringInterval": "60",
Maybe we can start with 15 or 30

2022-10-05 17:14 UTC, marcomarasca requested changes
See comments

2022-10-06 20:42 UTC, marcomarasca approved these changes

2022-10-07 23:58 UTC, xschildw commented on src/main/resources/templates/repo/main-repo-shared-resources-template.json.vpt
> +                "EnablePerformanceInsights": ${EnableRdsEnhancedMonitoring}
Moved this out of condition

2022-10-07 23:59 UTC, xschildw commented on src/test/java/org/sagebionetworks/template/repo/RepositoryTemplateBuilderImplTest.java
> +		validateResouceDatabaseInstance(resources, stack, "true");
Added missing check

2022-10-08 00:02 UTC, xschildw commented on src/test/java/org/sagebionetworks/template/repo/RepositoryTemplateBuilderImplTest.java
> +		assertEquals(Boolean.parseBoolean(enableEnhancedMonitoring), props.get("EnablePerformanceInsights"));
Moved out of condition

2022-10-08 00:36 UTC, marcomarasca approved these changes

2022-10-08 00:37 UTC, merged